## Name: Zaidan Mufaddhal
## Student ID: AIU20092029

In [8]:
#Importing libraries
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [9]:
#Original dataset
datasetOriginal = pd.read_csv('Downloads/AAPL (1).csv')
datasetOriginal

Date        Open        High         Low       Close   Adj Close  \
0   2022-01-18  171.509995  172.539993  169.410004  169.800003  169.583939   
1   2022-01-19  170.000000  171.080002  165.940002  166.229996  166.018478   
2   2022-01-20  166.979996  169.679993  164.179993  164.509995  164.300659   
3   2022-01-21  164.419998  166.330002  162.300003  162.410004  162.203354   
4   2022-01-24  160.020004  162.300003  154.699997  161.619995  161.414337   
..         ...         ...         ...         ...         ...         ...   
57  2022-04-08  171.779999  171.779999  169.199997  170.089996  170.089996   
58  2022-04-11  168.710007  169.029999  165.500000  165.750000  165.750000   
59  2022-04-12  168.020004  169.869995  166.639999  167.660004  167.660004   
60  2022-04-13  167.389999  171.039993  166.770004  170.399994  170.399994   
61  2022-04-14  170.619995  171.270004  165.039993  165.289993  165.289993   

       Volume  
0    90956700  
1    94815000  
2    91420500  
3   122848900  
4   162294600  
..        ...  
57   76515900  
58   72246700  
59   79265200  
60   70618900  
61   75237500  

[62 rows x 7 columns]

In [10]:
#Dataset used for training and testing
dataset=datasetOriginal[['Open','High','Low','Close']]

In [11]:
dataset.describe()

Open        High         Low       Close
count   62.000000   62.000000   62.000000   62.000000
mean   167.475806  169.593871  165.282580  167.552420
std      6.524649    5.970880    6.822499    6.541811
min    150.899994  154.119995  150.100006  150.619995
25%    163.502499  165.194996  160.037495  163.004997
50%    168.245002  170.444999  166.065002  168.150001
75%    172.090000  174.130001  170.572495  172.729996
max    178.550003  179.610001  176.699997  178.960007

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    62 non-null     float64
 1   High    62 non-null     float64
 2   Low     62 non-null     float64
 3   Close   62 non-null     float64
dtypes: float64(4)
memory usage: 2.1 KB


In [14]:
#Extracting Independent and dependent Variable 
#Independent variables are Open, High, and Low
#Dependent variable is Close
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values 

In [15]:
print(x)

[[171.509995 172.539993 169.410004]
 [170.       171.080002 165.940002]
 [166.979996 169.679993 164.179993]
 [164.419998 166.330002 162.300003]
 [160.020004 162.300003 154.699997]
 [158.979996 162.759995 157.020004]
 [163.5      164.389999 157.820007]
 [162.449997 163.839996 158.279999]
 [165.710007 170.350006 162.800003]
 [170.160004 175.       169.509995]
 [174.009995 174.839996 172.309998]
 [174.75     175.880005 173.330002]
 [174.479996 176.240005 172.119995]
 [171.679993 174.100006 170.679993]
 [172.860001 173.949997 170.949997]
 [171.729996 175.350006 171.429993]
 [176.050003 176.649994 174.899994]
 [174.139999 175.479996 171.550003]
 [172.330002 173.080002 168.039993]
 [167.369995 169.580002 166.559998]
 [170.970001 172.949997 170.25    ]
 [171.850006 173.339996 170.050003]
 [171.029999 171.910004 168.470001]
 [169.820007 170.539993 166.190002]
 [164.979996 166.690002 162.149994]
 [165.539993 166.149994 159.75    ]
 [152.580002 162.850006 152.      ]
 [163.839996 165.119995 160.

In [16]:
print(y)

[169.800003 166.229996 164.509995 162.410004 161.619995 159.779999
 159.690002 159.220001 170.330002 174.779999 174.610001 175.839996
 172.899994 172.389999 171.660004 174.830002 176.279999 172.119995
 168.639999 168.880005 172.789993 172.550003 168.880005 167.300003
 164.320007 160.070007 162.740005 164.850006 165.119995 163.199997
 166.559998 166.229996 163.169998 159.300003 157.440002 162.949997
 158.520004 154.729996 150.619995 155.089996 159.589996 160.619995
 163.979996 165.380005 168.820007 170.210007 174.070007 174.720001
 175.600006 178.960007 177.770004 174.610001 174.309998 178.440002
 175.059998 171.830002 172.139999 170.089996 165.75     167.660004
 170.399994 165.289993]


In [106]:
# Splitting the dataset into training and test set. 
# Splitting into 70% as training set, 30% as test set
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.3, random_state=0)  

In [107]:
x_train

array([[172.860001, 173.949997, 170.949997],
       [174.029999, 174.880005, 171.940002],
       [171.029999, 171.910004, 168.470001],
       [168.470001, 168.910004, 165.550003],
       [160.509995, 164.479996, 159.759995],
       [157.050003, 160.      , 154.460007],
       [171.160004, 173.360001, 169.850006],
       [172.330002, 173.080002, 168.039993],
       [168.710007, 169.029999, 165.5     ],
       [164.699997, 166.600006, 161.970001],
       [171.729996, 175.350006, 171.429993],
       [158.979996, 162.759995, 157.020004],
       [168.020004, 169.869995, 166.639999],
       [176.050003, 176.649994, 174.899994],
       [170.970001, 172.949997, 170.25    ],
       [177.5     , 178.300003, 174.419998],
       [165.710007, 170.350006, 162.800003],
       [171.679993, 174.100006, 170.679993],
       [165.539993, 166.149994, 159.75    ],
       [158.929993, 159.279999, 154.5     ],
       [174.139999, 175.479996, 171.550003],
       [171.059998, 174.139999, 170.210007],
       [17

In [108]:
x_test

array([[164.389999, 167.360001, 162.949997],
       [164.490005, 165.550003, 162.100006],
       [163.360001, 165.020004, 159.039993],
       [172.169998, 175.729996, 172.      ],
       [177.839996, 178.029999, 174.399994],
       [161.479996, 163.410004, 159.410004],
       [174.75    , 175.880005, 173.330002],
       [167.990005, 172.639999, 167.649994],
       [166.979996, 169.679993, 164.179993],
       [163.509995, 166.350006, 163.009995],
       [152.580002, 162.850006, 152.      ],
       [160.020004, 162.300003, 154.699997],
       [174.009995, 174.839996, 172.309998],
       [158.610001, 161.      , 157.630005],
       [163.059998, 165.419998, 162.429993],
       [158.820007, 162.880005, 155.800003],
       [170.619995, 171.270004, 165.039993],
       [163.839996, 165.119995, 160.869995],
       [162.449997, 163.839996, 158.279999]])

In [109]:
#Fitting the MLR model to the training set  
from sklearn.linear_model import LinearRegression  

In [111]:
regressor= LinearRegression()
regressor.fit(x_train, y_train) 

LinearRegression()

In [112]:
#Predicting the Test set result 
y_pred= regressor.predict(x_test)  

In [113]:
y_pred

array([165.98731625, 163.04914973, 161.11729258, 175.67020996,
       174.8904301 , 161.25689616, 174.41803069, 172.56254041,
       167.2663436 , 165.65559353, 163.3380171 , 157.66160108,
       173.07937932, 159.71040647, 164.51371116, 160.3599524 ,
       166.37507117, 162.19780798, 159.97358352])

In [114]:
y_test

array([166.559998, 163.169998, 159.300003, 175.600006, 174.610001,
       162.949997, 175.839996, 170.210007, 164.509995, 165.380005,
       162.740005, 161.619995, 174.610001, 160.619995, 165.119995,
       157.440002, 165.289993, 164.850006, 159.220001])

In [115]:
#Predicting the Train set result
y_tpred=regressor.predict(x_train)

In [116]:
y_tpred

array([172.04977169, 172.82179838, 169.41401482, 165.97608437,
       163.74554005, 157.53686714, 172.10891375, 169.2509265 ,
       165.85290552, 164.01476121, 175.19016906, 161.00787254,
       168.40890299, 175.32232098, 172.1056667 , 175.55641637,
       168.21812043, 173.14843991, 160.94905177, 154.90370316,
       173.13843028, 173.42455555, 178.67465834, 171.50568116,
       152.41121893, 167.43544026, 174.17248917, 170.52301903,
       163.99544158, 159.27793779, 167.14952513, 156.17714551,
       177.90128761, 171.58081307, 168.61777057, 174.77920719,
       154.90303798, 169.1066462 , 164.2121384 , 170.44425542,
       178.5993621 , 174.07542684, 168.92227951])

In [117]:
y_train

array([171.660004, 174.309998, 168.880005, 166.229996, 163.979996,
       159.589996, 172.139999, 168.639999, 165.75    , 163.199997,
       174.830002, 159.779999, 167.660004, 176.279999, 172.789993,
       175.059998, 170.330002, 172.389999, 160.070007, 154.729996,
       172.119995, 174.070007, 178.960007, 171.830002, 150.619995,
       166.229996, 172.899994, 170.399994, 164.320007, 159.690002,
       167.300003, 158.520004, 177.770004, 172.550003, 168.880005,
       174.779999, 155.089996, 170.089996, 162.410004, 169.800003,
       178.440002, 174.720001, 168.820007])

In [118]:
#Printing the Train set and Test set scores
print('Train Score: ', regressor.score(x_train, y_train))  
print('Test Score: ', regressor.score(x_test, y_test))  

Train Score:  0.9804723399199823
Test Score:  0.9021250696977647


In [119]:
import sklearn.metrics as sm

# Compute performance metrics
print("Linear regressor performance:")
print("R2 score =", round(sm.r2_score(y_test, y_pred), 2))

Linear regressor performance:
R2 score = 0.9


*So, the Linear Regressor performance is 90% Accuracy*

## Visualize the original dataset

In [137]:
import numpy as np  
from bokeh.plotting import figure, output_file, show

In [138]:
# instantiating the figure object
graph = figure(x_axis_type = "datetime", title = "Apple Stock Closing Prices")

In [139]:
# name of the x-axis
graph.xaxis.axis_label = 'Date'
   
# name of the y-axis
graph.yaxis.axis_label = 'Price (in USD)'

In [140]:
#Combining the original dataset of testing and training
import pandas as pd
originalResult = np.concatenate((y_train, y_test))

In [141]:
# plotting the line graph for Original Dataset
x_axis_coordinates = np.array(datasetOriginal['Date'], dtype = np.datetime64)
y_axis_coordinates = originalResult
color = "blue"
legend_label = 'Original'
graph.line(x_axis_coordinates,
        y_axis_coordinates,
        color = color,
        legend_label = legend_label)

GlyphRenderer(id='5035', ...)

## Visualize the predicted dataset

In [142]:
#Combining the prediction data of testing and training
import pandas as pd
predictionResult = np.concatenate((y_tpred, y_pred))

In [143]:
# plotting the line graph for Original Dataset
x_axis_coordinates = np.array(datasetOriginal['Date'], dtype = np.datetime64)
y_axis_coordinates = predictionResult
color = "red"
legend_label = 'Prediction'
graph.line(x_axis_coordinates,
        y_axis_coordinates,
        color = color,
        legend_label = legend_label)

GlyphRenderer(id='5067', ...)

In [144]:
graph.legend.location = "top_left"

In [145]:
show(graph)

In [130]:
predictionResult

array([172.04977169, 172.82179838, 169.41401482, 165.97608437,
       163.74554005, 157.53686714, 172.10891375, 169.2509265 ,
       165.85290552, 164.01476121, 175.19016906, 161.00787254,
       168.40890299, 175.32232098, 172.1056667 , 175.55641637,
       168.21812043, 173.14843991, 160.94905177, 154.90370316,
       173.13843028, 173.42455555, 178.67465834, 171.50568116,
       152.41121893, 167.43544026, 174.17248917, 170.52301903,
       163.99544158, 159.27793779, 167.14952513, 156.17714551,
       177.90128761, 171.58081307, 168.61777057, 174.77920719,
       154.90303798, 169.1066462 , 164.2121384 , 170.44425542,
       178.5993621 , 174.07542684, 168.92227951, 165.98731625,
       163.04914973, 161.11729258, 175.67020996, 174.8904301 ,
       161.25689616, 174.41803069, 172.56254041, 167.2663436 ,
       165.65559353, 163.3380171 , 157.66160108, 173.07937932,
       159.71040647, 164.51371116, 160.3599524 , 166.37507117,
       162.19780798, 159.97358352])

In [131]:
originalResult

array([171.660004, 174.309998, 168.880005, 166.229996, 163.979996,
       159.589996, 172.139999, 168.639999, 165.75    , 163.199997,
       174.830002, 159.779999, 167.660004, 176.279999, 172.789993,
       175.059998, 170.330002, 172.389999, 160.070007, 154.729996,
       172.119995, 174.070007, 178.960007, 171.830002, 150.619995,
       166.229996, 172.899994, 170.399994, 164.320007, 159.690002,
       167.300003, 158.520004, 177.770004, 172.550003, 168.880005,
       174.779999, 155.089996, 170.089996, 162.410004, 169.800003,
       178.440002, 174.720001, 168.820007, 166.559998, 163.169998,
       159.300003, 175.600006, 174.610001, 162.949997, 175.839996,
       170.210007, 164.509995, 165.380005, 162.740005, 161.619995,
       174.610001, 160.619995, 165.119995, 157.440002, 165.289993,
       164.850006, 159.220001])